# Generated by Django 5.2.8 on 2025-11-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('self_help', 'Self-Help'), ('romance', 'Romance'), ('trading_finance', 'Trading & Finance'), ('hindi', 'Hindi Books'), ('kids', 'Kids Books'), ('manga', 'Manga'), ('mythology', 'Mythology'), ('science', 'Science'), ('biography', 'Biography & Autobiography'), ('robert_green_special', 'Robert Green Special'), ('new_arrivals', 'New Arrivals'), ('preloved_bestsellers', 'Preloved Bestsellers')], default='self_help', max_length=50),
        ),
    ]
