# Generated by Django 5.2.8 on 2025-12-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('manga_comics', 'MANGA & COMICS'), ('most_read_combos', 'MOST READ COMBOS'), ('check_reviews', 'CHECK OUR REVIEWS'), ('self_improvements', 'SELF IMPROVEMENTS'), ('romance', 'ROMANCE ON SALE'), ('hindi', 'HINDI BOOKS'), ('business_stock_market', 'BUSINESS & STOCK-MARKET'), ('new_arrivals', 'NEW ARRIVALS')], default='self_help', max_length=50),
        ),
    ]
