# Generated by Django 5.2.8 on 2025-12-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0003_marvelcomic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MarvelComic',
        ),
        migrations.AlterField(
            model_name='product_variety',
            name='type',
            field=models.CharField(choices=[('NEW', 'NEW ARRIVALS'), ('MNG', 'MANGA & COMICS'), ('MRC', 'MOST READ COMBOS'), ('SFI', 'SELF IMPROVEMENTS'), ('ROS', 'ROMANCE ON SALE'), ('HIN', 'HINDI BOOKS'), ('BSM', 'BUSINESS & STOCK-MARKET')], max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_categories.product_variety'),
        ),
    ]
