# Generated by Django 5.2.8 on 2025-12-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0004_product_delete_marvelcomic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product_variety',
            name='type',
            field=models.CharField(choices=[('NEW', 'NEW ARRIVAL'), ('MNG', 'MANGA & COMICS'), ('MRC', 'MOST READ COMBOS'), ('SFI', 'SELF IMPROVEMENTS'), ('ROS', 'ROMANCE ON SALE'), ('HIN', 'HINDI BOOKS'), ('BSM', 'BUSINESS & STOCK-MARKET')], max_length=4, unique=True),
        ),
    ]
