# Generated by Django 5.2.8 on 2025-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_order_upay_payment_status_order_upay_response_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='upay_transaction_id',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='upay_payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='upay_response_data',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
