# Generated by Django 5.2.8 on 2025-12-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_upay_transaction_id_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
